#!/bin/bash
/usr/bin/overviewer.py --config=/var/lib/minecraft/overviewer-config.py
/usr/bin/overviewer.py --genpoi --config=/var/lib/minecraft/overviewer-config.py
echo "{}" > /var/www/overviewer/progress.json
